        
jobs:
  - job: job_core_deploy
    displayName: Common Resources Deploy

    steps:
      - task: AzureCLI@2
        name: task_core_deploy
        displayName: 'Deploy Core Resources'
        inputs:
          azureSubscription: ${{ parameters.p_service_connection }}
          scriptType: 'pscore'
          scriptLocation: 'scriptPath'
          scriptPath: 'scripts/core.ps1'
          arguments: '-mode ${{ parameters.p_deployment_mode }} -tenantName ${{ parameters.p_tenant_name }} -resourceGroup $(alertsResourceGroupName)'
